package Reto01Acceso;

import java.io.*;
import javax.swing.*;

/**
 *
 * @author Oscar Revuelta
 */
public class BlocDeNotas extends javax.swing.JFrame {
    

    /**
     *
     */
    private File ficheroActual;

    /**
     *
     */
    public BlocDeNotas() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        textareaContenido = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        miNuevo = new javax.swing.JMenuItem();
        miAbrir = new javax.swing.JMenuItem();
        miGuardar = new javax.swing.JMenuItem();
        miGuardarComo = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bloc de notas");
        setIconImage(new ImageIcon(getClass().getResource("/Reto01Acceso/imagenes/IconoBlocDeNotas.png")).getImage());

        textareaContenido.setColumns(20);
        textareaContenido.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        textareaContenido.setRows(5);
        jScrollPane1.setViewportView(textareaContenido);

        jMenu1.setText("Archivo");

        miNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Reto01Acceso/imagenes/IconoNuevo.png"))); // NOI18N
        miNuevo.setText("Nuevo");
        miNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miNuevoActionPerformed(evt);
            }
        });
        jMenu1.add(miNuevo);

        miAbrir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Reto01Acceso/imagenes/IconoAbrir.png"))); // NOI18N
        miAbrir.setText("Abrir");
        miAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miAbrirActionPerformed(evt);
            }
        });
        jMenu1.add(miAbrir);

        miGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Reto01Acceso/imagenes/IconoGuardar.png"))); // NOI18N
        miGuardar.setText("Guardar");
        miGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miGuardarActionPerformed(evt);
            }
        });
        jMenu1.add(miGuardar);

        miGuardarComo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Reto01Acceso/imagenes/IconoGuardar.png"))); // NOI18N
        miGuardarComo.setText("Guardar como...");
        miGuardarComo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miGuardarComoActionPerformed(evt);
            }
        });
        jMenu1.add(miGuardarComo);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 692, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 552, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void miNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miNuevoActionPerformed
        this.textareaContenido.setText("");
        this.ficheroActual = null;

    }//GEN-LAST:event_miNuevoActionPerformed

    private void miAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miAbrirActionPerformed
        JFileChooser fc = new JFileChooser();

        //fc.setMultiSelectionEnabled(false);
        int seleccion = fc.showOpenDialog(this.getContentPane());
        //fc.setFileSelectionMode(JFileChooser.FILES_ONLY);

        if (seleccion == JFileChooser.APPROVE_OPTION) {

            this.ficheroActual = fc.getSelectedFile();

            try (FileReader fr = new FileReader(this.ficheroActual)) {
                String cadena = "";
                int valor = fr.read();
                while (valor != -1) {
                    cadena += (char) valor;
                    valor = fr.read();
                }
                this.textareaContenido.setText(cadena);

            } catch (FileNotFoundException ex) {
                System.out.println(ex.getMessage());
            } catch (IOException ex) {
                System.out.println(ex.getMessage());
            }

        }
    }//GEN-LAST:event_miAbrirActionPerformed

    private void miGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miGuardarActionPerformed
        if (this.ficheroActual == null) {

            this.abrirVentanaGuardar();

        } else {

            this.escribirFichero();

        }
    }//GEN-LAST:event_miGuardarActionPerformed

    private void miGuardarComoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miGuardarComoActionPerformed
        this.abrirVentanaGuardar();
    }//GEN-LAST:event_miGuardarComoActionPerformed

    /**
     *
     */
    private void abrirVentanaGuardar() {
        JFileChooser fc = new JFileChooser();

        fc.setMultiSelectionEnabled(false);
        fc.setFileSelectionMode(JFileChooser.FILES_ONLY);
        int seleccion = fc.showSaveDialog(this.getContentPane());

        if (seleccion == JFileChooser.APPROVE_OPTION) {

            this.ficheroActual = fc.getSelectedFile();
            if (ficheroActual.exists()) {
                    int opciones = JOptionPane.showConfirmDialog(BlocDeNotas.this, "El archivo ya existe. ¿Desea sobrescribirlo?", "Confirmar Sobrescritura", JOptionPane.YES_NO_OPTION);
                    if (opciones == JOptionPane.NO_OPTION) {
                        return;
                    }
                }
                try (PrintWriter writer = new PrintWriter(ficheroActual)) {
                    writer.print(textareaContenido.getText());
                } catch (IOException ex) {
                }

            this.escribirFichero();

        }
    }

    /**
     *
     */
    private void escribirFichero() {
        try (FileWriter fw = new FileWriter(this.ficheroActual)) {

            fw.write(this.textareaContenido.getText());

        } catch (IOException ex) {
            Logger.getLogger(BlocDeNotas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    

    /**
     *
     * @param args
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BlocDeNotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BlocDeNotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BlocDeNotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BlocDeNotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BlocDeNotas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem miAbrir;
    private javax.swing.JMenuItem miGuardar;
    private javax.swing.JMenuItem miGuardarComo;
    private javax.swing.JMenuItem miNuevo;
    private javax.swing.JTextArea textareaContenido;
    // End of variables declaration//GEN-END:variables
}
